### PR TITLE
Use a Docker-based GitHub Action for CI

### LINKED ISSUE #12: Use GitHub Actions for continuous integration
Currently, we have a few tests, but they need to be run manually and are time-consuming. It would be useful to have continuous integration so that we can be sure that changes to the code or package updates won't break anything. 

[Here's](https://github.com/audrow/now-and-later) an example repository using Actions for reference.

### PR DESCRIPTION
**Pull request by emilyxzhou**
Fixes #12. The Dockerfile sets up all of Cordial's dependencies and runs its integration tests in the entrypoint script. The action.yml file defines an action using the Dockerfile, which is then called in the workflow file; the workflow is triggered whenever commits are pushed to the repository or a pull request is made.

### CODE REVIEW

**Review by audrow — COMMENTED** [review]
Looks great, but can you figure out a better spot for `Dockerfile`, `action.yml`, and `run_tests.sh` to go? They are specific to being used with Github actions, so they probably shouldn't be on the top level. Also, I could imagine us having another Dockerfile associated with this repository that helps people to run it easily in the near future.

**Comment by audrow** [comment]
Maybe put `Dockerfile`, `action.yml`, and `run_tests.sh` in a folder called `ci`?

**Comment by emilyxzhou** [comment]
I've moved `Dockerfile`, `action.yml`, and `run_tests.sh` to the `./.github/actions/run-tests-action` directory. Instead of using the `COPY` command in the Dockerfile, I cloned the repository in the parent image so that the container has access to the tests. Since this repository doesn't yet have a launch file containing all of the tests, I modified `run_tests.sh` to run `rostest` separately for each test.

**Review by audrow — APPROVED** [review]
Looks good, LGTM!

**Pull request merged**
